### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by mattstauffer** [phildini/technicalmajority#1]
I created a similar project with A) less info and B) no good domain yet. I'd gladly just merge the two and call mine defunct.

It's here right now:

https://staywokeorg.github.io/tech-forward/

Some ideas:

1. Are you interested in this being a StayWoke project? The benefit is it would go under their GitHub username and likely bring more helpers from their world. The ... opposite of benefit is it's no longer under your name quite so much.
2. Do you like people editing straight HTML? I set mine up to pull from JSON.. easier for people to edit but probably no good for Search engine indexing/folks without javascript (was planning to eventually hook the JSON into a build system)  e.g. https://github.com/StayWokeOrg/tech-forward/blob/master/js/orgs.json
3. We could also bring over the template I used on the tech forward thing in whatever final amalgamation we set up of the two.

I'm down for whatever you want. If you're going to keep this up, I don't see any reason for me to maintain one separately, so basically I just want to see what I can offer you before I shut mine down.

**Comment by phildini** [comment]
Hey! Thanks for reaching out.

1. I think I'm pretty deliberately not associating this with any particular group. I'm in DevProgress and Ragtag and ProgCoders and Tech Solidarity, and I'm pretty convinced that I want people from all those groups (and yours!) contributing, and putting it under any one of those groups might seem limiting to that group. I care less about it being "my name", and more about sending the signal that all are welcome.

2. Right now it's straight html because that's the simplest scaling solution. If you have thoughts on how to change that, I'm definitely open. My only real "rule" in that direction right now is that it has to be either static-site-generator style, or backed by a db. (So, the version where it's all in JSON/JS is fine by me, so long as we can output the static site to serve via github pages)

3. _makes flailing noises_. I would like it to look better than it does right now, but don't have clear direction on that, and am 100% open to ideas. The things I like about my current version are that each item has a little description, and space for multiple links. Yours is somewhat easier to navigate, is there a happy medium we could find? 

Yes, I'm planning on keeping this going as long as I possibly can, and sharing it heavily once I get some more content there. I'm 100% open to ideas and suggestions and any collaborators you want to bring on.

**Comment by mattstauffer** [comment]
:)

1. Perfect. Makes sense!
2. Cool! 
3. Ha! Sounds like if I can adjust my design to allow for descriptions and links you might be OK if I just PR my whole app into yours?

**Comment by mattstauffer** [comment]
Updated mine with your data and to show more info. Thoughts?

https://staywokeorg.github.io/tech-forward/
